Algoritmo "Habilitação"
Var
idade:inteiro
nome:caractere
Inicio
escreval("Olá , seja bem vindo ")
escreval("Vamos descobrir se você pode tirar sua habiilitação ?")
escreval("Primeiro passo é nos informar seu nome")
leia(nome)
escreval("Agora nos informe sua idade")
leia(idade)
se idade >=18 entao
escreval (nome, " você pode tirar a habilitação !")
senao
escreval (nome, " você não pode tirar a sua habilitação")
fimse
Fimalgoritmo